// AUTO_GENERATED BY JavaPoet
package output;

import testPackage.Test1;
import testPackage.Test2;

public class Fac {
  private Test1 test1;

  private Test2 test2;

  public Fac(Test1 test1, Test2 test2) {
    this.test1 = test1;
    this.test2 = test2;
  }
}
