// AUTO_GENERATED BY JavaPoet
package output;

import java.lang.String;
import testPackage.Circle;
import testPackage.Shape;
import testPackage.Square;

public class FactM {
  public Shape factoryMethod(String prod) {
    if (prod.equals("Circle")) {
      return new Circle();
    } else if (prod.equals("Square")) {
      return new Square();
    } else {
      return null;
    }
  }
}
