// AUTO_GENERATED BY JavaPoet
package output;

import java.lang.Override;

public class Mediate implements Elements {
  private ElemA elema;

  private ElemB elemb;

  @Override
  public void regElemA(ElemA elema) {
    this.elema = elema;
  }

  @Override
  public void regElemB(ElemB elemb) {
    this.elemb = elemb;
  }
}
