// AUTO_GENERATED BY JavaPoet
package output;

public abstract class TempMethod {
  public abstract void first();

  public abstract void second();

  public abstract void third();

  public final void templateMethod() {
    first();
    second();
    third();
  }
}
